### PR TITLE
Correct embedded-hal 1.0 implementation and other cleanups

### PR DESCRIPTION
**Pull request by dimpolo**
* use transaction in i2c and spi implemenations
* remove error type in CountDown trait
* cleanup

@yanshay if you happen to have some time, maybe you could give this branch a try and see if I messed something up :)

### CODE REVIEW

**Comment by yanshay** [comment]
I tried it and it just hangs, I can see `start` of CountDown called but not the wait.
Maybe it is due to changing to transaction. In the past that didn't work on esp32, I think they had fixed it but maybe they didn't. 
I'll try to debug this, will take some time.

**Comment by dimpolo** [comment]
Thanks for taking a look!
You'll probably need this https://github.com/esp-rs/esp-hal/pull/2028
Are you using esp-hal 0.21.0 or newer?

**Comment by yanshay** [comment]
forget what I wrote, it works fine until the last commit of `remove Error Type from CountDown`.
I don't understand how it should work.
Previously the 'wait' fn checked if time passed or not and returned either an Err or Ok based on that.
Now it can return only Ok (because of Infallible), but the code calling it is still checking for error case.
I tried dong a busy wait inside the fn waiting, but this doesn't work.

So how should I change my CountDown code to get it to work?

**Comment by dimpolo** [comment]
Ah yes!

Try this:
```rust
struct TimerWrapper<'a, T> {
    timer: PeriodicTimer<'a, T>,
}

impl<'a, TIM> CountDown for TimerWrapper<'a, TIM>
where
    TIM: esp_hal::timer::Timer,
{
    type Time = MicrosDurationU64;
    fn start<T>(&mut self, timeout: T)
    where
        T: Into<Self::Time>,
    {
        self.timer.start(timeout.into()).unwrap();
    }

    fn wait(&mut self) -> nb::Result<(), Infallible> {
        // convert nb::Result<(), void::Void> to nb::Result<(), Infallible>
        match self.timer.wait() {
            Ok(_) => Ok(()),
            Err(_) => Err(nb::Error::WouldBlock),
        }
    }
}

let timg0 = TimerGroup::new(peripherals.TIMG0);
let timer = TimerWrapper { timer: PeriodicTimer::new(timg0.timer0) };
```

**Comment by yanshay** [comment]
Ok, that `Infallible` got me confused, I thought I can't return an `Err` but I see `nb::Result` is different than `Result`. 
Got it to work also with my own code.

I don't know if there's an example but that point best if documented with an example as it's confusing.

**Comment by dimpolo** [comment]
Thank you!
Yeah I'll add an example

**Comment by yanshay** [comment]
Let me know once it's final, I'll need to rebase my async changes on top of these changes, I hope it's not going to be too complex with these changes.

**Comment by yanshay** [comment]
Why did you choose to change the `write` signature to require data to be `mut`?

Technically it is required to use Transaction, but is there any benefit to using `spi.transaction` instead of the simple `spi.write` when this forces the client to have the data as mutable which is not always the case?

**Comment by dimpolo** [comment]
> Why did you choose to change the `write` signature to require data to be `mut`?
> 
> Technically it is required to use Transaction, but is there any benefit to using `spi.transaction` instead of the simple `spi.write` when this forces the client to have the data as mutable which is not always the case?

Only `transaction` will have the correct CS behaviour

I published 0.5.0, so if you'd like you can send the async PR :)

**Comment by yanshay** [comment]
> I published 0.5.0, so if you'd like you can send the async PR :)

The I2C is done (well, for a first version).
I'm now doing the SPI.
It should be very similar and almost exact same code as sync, however it doesn't work.
I'm using esp32, and currently only DMA is supported as async with Esp32.
What I see is that when waiting for ack, [2, 0] is submitted and the device returns [8,0].
I can't find in the PN532 docs what does `8` mean to understand what is wrong there.
Do you know?

**Comment by dimpolo** [comment]
That's very strange.

After sending [2,0] the response you would expect is [0, 1].
Note that the response byte is the second byte and not the first.
Could it be the 8 is from some previous response?

**Comment by yanshay** [comment]
I made some progress.
I've been told by the esp-Hal team that Esp32 has issues with DMA. So I switched to Esp32S3.

The what happens is that if I run the async version, I get [8,8] all the time when checking status.

If I first run the sync version and then flash (without powering off) with the async version then it works perfectly.

This is very strange, maybe the DMA SPI is a bit different and for the initialization it is different enough not to work but after it's initialized (by the async) then it works.

I will try tomorrow using DMA in sync if it's possible and see if it's the DMA or something I'm not seeing in my code that is causing it.

**Comment by yanshay** [comment]
Actually, I had a mistake in my tests.
My async and sync programs were a bit different, which led me to believe they behaved differently.

So it goes back to the **sync** with version 0.5, w/o any changes, not behaving properly for me.

The first time (after power on) `sam_configuration` returns with an error, due to `wait_ready` not returning ready.j
If I stop there and do it again, it will still return the same error.

However, if I ignore that and continue to get device firmware, the firmware responds properly, and then I can scan tag as well.
And after that, `sam_configuration` will also work.

WDYT?

**Comment by dimpolo** [comment]
Thanks so much for doing all this!

I have one idea. Maybe you send the sam_configuration too quickly after power on and the PN532 isn't fully booted yet?
Also those `08` on the MISO look strange to me. Did you select SPI Mode0?

Is there somewhere I could take a look at your implementation?

**Comment by dimpolo** [comment]
> Did you select SPI Mode0?
Also in pulseview?

**Comment by yanshay** [comment]
> I have one idea. Maybe you send the sam_configuration too quickly after power on and the PN532 isn't fully booted yet?
> Also those `08` on the MISO look strange to me. Did you select SPI Mode0?

PN532 boots once I power it up, it takes time until I run the code (flash and run). Anyway, I added a 5sec delay at start and it didn't help.

I checked with ChatGPT what that 8 means, not sure it really knows aything correct, but it claims that code mean the pn532 has prior data to send, potentially from previous operation (which is sam_config in my case). It could be totally off, but maybe you know about that?

I'm using Mode0 and in pulseview it is set to Clock polarity 0 and Clock phase 0. I think that's Mode0. It is also set to Lsb and the data seems correct.

Application I'm testing with is attached. It is quite a mess due to all kind of tests, but current state is what I tested latest.
[esp32-nfc-pull25.zip](https://github.com/user-attachments/files/18189209/esp32-nfc-pull25.zip)
Do you happen to have an esp32 (preferably S3) to run it on?
Do you have an application you used to test SPI?

Also a question: The way the code checks for ready is by sending two bytes, and reads two bytes at the same time.
Doesn't that mean there's an extra 0 sent that isn't required? Maybe it has some affect?

**Comment by yanshay** [comment]
> Things break after a ESP32 reboot
In my case the first run fails and after a reboot it starts working (assuming I had let it continue the first run beyond the `sam_config` to the firmware query that always work.
Do you see a different behavior?
Keep in mind that to see this need to (1) flash some other program (hello-world) to the device and run it (2) disconnect power (so everything including pn532 will reset) and only then after turning everything on (3) flash the code being tested. So not to have the first initialization run when turning on the device.

> Can you confirm that adding pn532.interface.write(&mut []).unwrap();
It doesn't help in my case, neither for esp32s3 nor esp32.
I also tried forcing MOSI to Low and High as an output pin at the beginning, that didn't help either.

Did you use the same gpio I used or different ones? (the esp32s3 I have is with a display so I have limited pins to choose from)

**Comment by yanshay** [comment]
I think I found it, by going through the code at https://github.com/elechouse/PN532/blob/PN532_HSU/PN532_SPI/PN532_SPI.cpp .

There's a wake-up to Spi.
Need to add before working with pn532:

```
    cs.set_low();
    delay.delay_millis(2); 
    cs.set_high();
```

It works for me, can you confirm the same on your setup?

**Comment by yanshay** [comment]
I added 'wake_up' on my branch and completed a first version of async (both I2C and SPI).
I see you continue to updated the master branch. I need to merge all changed made in the last few days.
Let me know when you are done to merge at a stable point to start checking it out.

**Pull request merged**
